language: generic

sudo: false

services:
  - docker

addons:
  apt:
    packages:
      - xsltproc

before_install:
  - docker pull nevstokes/php-src:hashes

script:
  - make build

env:
  matrix:
    secure: Ld+xLjvO5jL+uxOmiBngiPCDhZ2/IgUr4DZJhVqgZM+vlFP3hfVkAD5F7ozmF8ixX3WQKE4tf067+zEBMfSCfMZ2WH0ic1VnedM/z6ifqL9HFIFNfR6A7F+cT/ViANvscUNh/cAeQkcX0zuSKK7jDBE/UHUbrDmGgK5xod0Hf2pj1XcAlVHGJfBawWcya955qAu4kQhIm1iZ3Cw9m9LuURVa/Yt0ypK01FRu92E1tamFe+ASXz1v5M3+2SqxlTJ5uIl6snZBzOn0uSPA++fILnF9gCubU9nyn9lwVkNG5WMteFeC1xN67G0A/5WIhjVzjxC0vCVM67lEGQJdeAD4Y50whGU3ptufBIooHlxvru+vuAesShB4rDGLStrId1tiMWr3lmOneiqk/bOOl6nSD/3LqiMITZqW5omjpLWzLLbCsLSkrKlsMuNHiDTmXnJwwt1gWqkjmgiS8WRp4pKel3mpoR8d8Zzbhu8ZwG/0bxTpL7mTbvOFeEsTM+5ALGNjS163DIARVBg3tAUciCIEzJHtAeHV7Huy4ft+HRCYGtzhaxU/yzE43lf+Xn1bjaCLGvBLDkanWFu1WDMAHexzdwbdUl/KLL0FZtx52aB7tudGWbZG6c8qpzl3lVccivqLCBltI0HSYYngsaWKslmHGaNH3csE7ez+vbuIbbNcNIg=
