language: generic

sudo: false

services:
  - docker

addons:
  apt:
    packages:
      - xsltproc

before_install:
  - docker pull nevstokes/php-src:hashes

script:
  - make build

env:
  matrix:
    - secure: WdeOpIKf8hwVt0xAv717/EvFoyYIItEQJsJesZbMOdRm+ejz/XDntRejZ+/PQGnpiMDV66OTCdVUA3r8IhgTb416V4Bgp1rss6jKSM7PFD5wzXYm2/G8aALiqqFTGYLUSLdd11usu9yC1nNP3h0QOjcGfeI1/n2545Yy1tASXc5EJPiWMtTxIBxiAK69hJKSDXkIcWfuUXYX4P3xZtC7n10UoDYfJqTvHBvNw2a7TQyEbKLyg3x2ieqYkLPoLBRoqJXLVo2YhoRckpM7gzT9+Nba7ooeucD8KR+BDY1+NpBM3gjW04I0cNclCWuc0LLJBZrR1g10yv6wDHlEGn/ya/8DfdCDuElQDY4fLFUKi5EdCmBj2K5rod81Lb8qFDRGv96qWv7udy+TcoF+lro2UyjlC6pdnip+Gf7XLCA29Bthp/W9VRzjJzgBUbzaOKetO226zWUFKgYpCjDVcGbIGZlF6o/Yc5RrN8t6d0aWJmWSHEsWesvczeKqJo+VU2wW/7X6rh3bRM1j8SOw5w8aTAj8I8LTwB34wg/d3NBIR8JJr9SBUatbSb5OKZsPoahgbC7lQ5gOK05wc9cUy8BOcktew2QypQNNdMcxxLCR/jV00jw99Mxnlb7cwVgzKexkMo5gih0PwX5Kuo9JTgfvhUnR1pxu5DpvYvSBZVdohhM=
    - secure: kSdwrNnJXbaIpcRM6o0CcELJ0gDj0o0HNzY4uVlbMd+PxE3qEBn5p9djVjOkaevkIYu70JvcyCw2G+D1OUokYjBMRNUb03/sFKOOIsRaOz4uSXinqpjsHqNHry6aoFG+C8ZE9yB1bWG2P7zJOiWVYLukCi4CTJCVFOz6/DrHrKT6T8G7F0VSt2DDHqLLzaag7pSlcfNJ7STWIRlYHILVPyI8hoSBLAvS31SYAlglSAUbplURMawKAJe0Xn9O21aSGtUsRo5I8PavdT844NUrw48PfNrFkYST4eZiARlUGOm+5JoJwXHCA1/zzYljBO2Lo/GyBlYIXR9NAy84lPS0lNUjJqUu0nHIBNDh4/FsxxqjzJ5zrtYQ8MJ9KMY753BCz2eab0LkH6e57+pktCnE93KNlhoSlHlWHgn4OmCTAk8uDS/iBc9BriSGLBaTcRC88nYcwb5Oclp7g76DVPt0VJysmcEp7uttQDggv9yqEBoTYQ0BEYoCavlwXxkXduDXJ1TVSulgR9yz+7uEICfP24JYgkpWNRgzcqxlHTn5AmSopuL0P4xZ+YDZ4Ey4qRrqrIZ2zNpkB+Pqny9zOMvm0iZwCuVC/Zmo2YYsEvHPbiJXD6xm9bD//+Jkev24m7pLWBj7ihWHKAkyqodpJQW+w6yMjoIw+YjQMSO3JBXGnhY=
    - secure: JJugpr2U84Mgdv49IgNLNIJwaLaa7RvLbZLV+CekfGei7EcyG6Lgc80d2O0ZcEzu/8kYeOfkAHouGwZOtFHgGqYJsOsClOLXiGlWXLOJBhbmWVZT1ST6xTXOtC2/h3CionXF5S+O51jggTQYT1d8GJlLBroHR2bKinBIgz02xXHY9MfuthmH5NbeWaX4kG2FMQuJghhprWRmWrJs7/Uhb5pE5d1gAAwzwYTVdC01wuH7wqzqW4uGmWWbeWOlKryNgxBhp2LIwB+7rOfavE5J6OZt25rWV6nATUdugGDXSaC+67hMBgiwalF8VthWykYdgIDbakNuNsLjLhOWB2AFiqbNuOnF0aKn9pRZ2Md5TnrODupJbhqOMAnCpLANmNmVKTEExL4V3tYtO8aFR37455awckNQ/45fXFF2F88rdcA52b/+wS/2aM/AoQNwvWC2FBh41XESOeIWTqYLmrwyYtpggSQfHZFXffBRUVGjHmvDdcFlXcb7zYD/6Cij42f16KYHZdCKFfBBu0rebv8O/x8hq5RJ4h55qGPJg9k/8x/JdNASlA+Rjtcx7qtl3VNmtEVus9NLBSCZqJ1Mfbn8OeK3CDzQfumIjrKrJQEsyACpS2t7g8qrO5buuRCAcFkBIWSRRmYCBegjabCmnzEDdnzwkD6Dtd6fuGqXDafv/tg=
