#!/usr/bin/env bash

feedUpdated=$(date -d $(wget -q https://secure.php.net/releases/feed.php -O - | xsltproc updated.xsl -) +%s)
imageBuilt=$(date -d $(docker inspect --format "{{ index .Config.Labels \"org.opencontainers.image.created\" }}" nevstokes/php-src:hashes) +%s)

if [ $feedUpdated -ge $imageBuilt ]; then
    docker build \
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
        --build-arg VCS_REF=`git rev-parse --short HEAD` \
        --build-arg VCS_URL=`git config --get remote.origin.url` \
        -t $IMAGE_NAME .

    if [[ $DOCKER_USERNAME && $DOCKER_PASSWORD ]]; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $IMAGE_NAME
    fi
else
    echo "No need to update version info"
fi
