#!/bin/bash

id=$(docker create nevstokes/php-src:hashes /)
docker cp $id:/versioninfo - | tar -xf - > versioninfo
docker rm -v $id > /dev/null

latestVersion=`cat versioninfo | sed -E 's/^([0-9]+\.[0-9]+).*/\1/' | sort -rg -t. -k1,1 -k2,2 | head -1`

echo "Latest v$latestVersion"

#if [[ $PHP_VERSION && "$latestVersion" == "$PHP_VERSION" ]]; then
#    docker tag $DOCKER_REPO:$PHP_VERSION $DOCKER_REPO:latest
#    docker push $DOCKER_REPO:latest
#fi

rm versioninfo